-- PAN (ID, Descripcion, Gluten)
INSERT INTO PAN VALUES (21, 'SESAMO', TRUE);
INSERT INTO PAN VALUES (22, 'CHAPATA', TRUE);
INSERT INTO PAN VALUES (23, 'CRISTAL', TRUE);
INSERT INTO PAN VALUES (24, 'MAIZ', FALSE);

-- HAMBURGUESA (ID, Nombre, Precio, IDP)
INSERT INTO HAMBURGUESA VALUES (1, 'CLASICA', 3.25, 21);
INSERT INTO HAMBURGUESA VALUES (2, 'HOLANDA', 4.25, 21);
INSERT INTO HAMBURGUESA VALUES (3, 'ALABAMA', 5.50, 23);
INSERT INTO HAMBURGUESA VALUES (4, 'TEXAS', 6.75, 21);
INSERT INTO HAMBURGUESA VALUES (5, 'COMPLETA', 6.25, 21);
INSERT INTO HAMBURGUESA VALUES (6, 'SERRANA', 6.25, 22);
INSERT INTO HAMBURGUESA VALUES (7, 'CELIACOS TERNERA', 4.75, 24);
INSERT INTO HAMBURGUESA VALUES (8, 'POLLO', 5.75, 23);
INSERT INTO HAMBURGUESA VALUES (9, 'CELIACOS POLLO', 4.40, 24);

-- INGREDIENTE (ID, Descripcion, Peso)
INSERT INTO INGREDIENTE VALUES (31, 'LECHUGA', 10);
INSERT INTO INGREDIENTE VALUES (32, 'TOMATE', 20);
INSERT INTO INGREDIENTE VALUES (33, 'CEBOLLA', 10);
INSERT INTO INGREDIENTE VALUES (34, 'QUESO', 20);
INSERT INTO INGREDIENTE VALUES (35, 'TERNERA', 125);
INSERT INTO INGREDIENTE VALUES (36, 'POLLO', 150);
INSERT INTO INGREDIENTE VALUES (37, 'BACON', 30);
INSERT INTO INGREDIENTE VALUES (38, 'CERDO', 125);
INSERT INTO INGREDIENTE VALUES (39, 'HUEVO', 50);
INSERT INTO INGREDIENTE VALUES (40, 'JAMON', 30);

-- INCORPORA (IDH, IDI, Cantidad)
INSERT INTO INCORPORA VALUES (1, 31, 1);
INSERT INTO INCORPORA VALUES (1, 32, 1);
INSERT INTO INCORPORA VALUES (1, 35, 1);

INSERT INTO INCORPORA VALUES (2, 31, 1);
INSERT INTO INCORPORA VALUES (2, 32, 1);
INSERT INTO INCORPORA VALUES (2, 34, 1);
INSERT INTO INCORPORA VALUES (2, 35, 1);

INSERT INTO INCORPORA VALUES (3, 31, 1);
INSERT INTO INCORPORA VALUES (3, 32, 1);
INSERT INTO INCORPORA VALUES (3, 33, 1);
INSERT INTO INCORPORA VALUES (3, 34, 1);
INSERT INTO INCORPORA VALUES (3, 35, 2);

INSERT INTO INCORPORA VALUES (4, 31, 1);
INSERT INTO INCORPORA VALUES (4, 32, 1);
INSERT INTO INCORPORA VALUES (4, 34, 1);
INSERT INTO INCORPORA VALUES (4, 37, 1);
INSERT INTO INCORPORA VALUES (4, 38, 1);

INSERT INTO INCORPORA VALUES (5, 31, 1);
INSERT INTO INCORPORA VALUES (5, 32, 1);
INSERT INTO INCORPORA VALUES (5, 34, 1);
INSERT INTO INCORPORA VALUES (5, 35, 2);
INSERT INTO INCORPORA VALUES (5, 39, 1);

INSERT INTO INCORPORA VALUES (6, 31, 1);
INSERT INTO INCORPORA VALUES (6, 32, 1);
INSERT INTO INCORPORA VALUES (6, 34, 1);
INSERT INTO INCORPORA VALUES (6, 37, 1);
INSERT INTO INCORPORA VALUES (6, 40, 1);

INSERT INTO INCORPORA VALUES (7, 31, 1);
INSERT INTO INCORPORA VALUES (7, 32, 1);
INSERT INTO INCORPORA VALUES (7, 33, 1);
INSERT INTO INCORPORA VALUES (7, 35, 1);

INSERT INTO INCORPORA VALUES (8, 31, 1);
INSERT INTO INCORPORA VALUES (8, 32, 1);
INSERT INTO INCORPORA VALUES (8, 33, 1);
INSERT INTO INCORPORA VALUES (8, 36, 1);
INSERT INTO INCORPORA VALUES (8, 37, 2);

INSERT INTO INCORPORA VALUES (9, 31, 1);
INSERT INTO INCORPORA VALUES (9, 32, 1);
INSERT INTO INCORPORA VALUES (9, 36, 1);
INSERT INTO INCORPORA VALUES (9, 37, 1);


COMMIT;

