DROP TABLE INCORPORA IF EXISTS;
DROP TABLE HAMBURGUESA IF EXISTS;
DROP TABLE INGREDIENTE IF EXISTS;
DROP TABLE PAN IF EXISTS;
DROP SEQUENCE IF EXISTS PAN_SEQ;
DROP SEQUENCE IF EXISTS HAMBURGUESA_SEQ;
DROP SEQUENCE IF EXISTS INGREDIENTE_SEQ;

CREATE SEQUENCE PAN_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE HAMBURGUESA_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE INGREDIENTE_SEQ START WITH 100 INCREMENT BY 1;


-- PAN (ID, Descripcion, Gluten)
CREATE TABLE PAN (
	ID BIGINT,
	Descripcion VARCHAR2(15),
	Gluten BOOLEAN,
	CONSTRAINT PK_PAN PRIMARY KEY (ID)
);

-- HAMBURGUESA (ID, Nombre, Precio, IDP)
CREATE TABLE HAMBURGUESA (
	ID BIGINT,
	Nombre VARCHAR2(20),
	Precio FLOAT,
	IDP BIGINT,
	CONSTRAINT PK_HAMBURGUESA PRIMARY KEY (ID),
	CONSTRAINT FK1_HAMBURGUESA FOREIGN KEY (IDP) REFERENCES PAN (ID),
	CONSTRAINT CK1_HAMBURGUESA CHECK ( Precio > 0 )
);

-- INGREDIENTE (ID, Descripcion, Peso)
CREATE TABLE INGREDIENTE (
	ID BIGINT,
	Descripcion VARCHAR2(15),
	Peso INTEGER,
	CONSTRAINT PK_INGREDIENTE PRIMARY KEY (ID),
	CONSTRAINT CK1_INGREDIENTE CHECK ( Peso > 0 )
);

-- INCORPORA (IDH, IDI, Cantidad)
CREATE TABLE INCORPORA (
	IDH BIGINT,
	IDI BIGINT,
	Cantidad INTEGER,
	CONSTRAINT PK_INCORPORA PRIMARY KEY (IDH, IDI),
	CONSTRAINT FK1_INCORPORA FOREIGN KEY (IDH) REFERENCES HAMBURGUESA (ID)
		ON DELETE CASCADE,
	CONSTRAINT FK2_INCORPORA FOREIGN KEY (IDI) REFERENCES INGREDIENTE (ID)
);

COMMIT;

